"""Initial migration

Revision ID: 0d8d41de00e4
Revises: f82ae04079fc
Create Date: 2025-03-24 14:05:49.559843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d8d41de00e4'
down_revision = 'f82ae04079fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('cost_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_price', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
